name: CI
on:
  push:
    branches:
      - master # need to filter here so we only deploy when there is a push to master
  # no filters on pull requests, so intentionally left blank
  pull_request: 

jobs:     
  build-site:
    if: ( github.event.commits[0].message != 'Initial commit' ) || github.run_number > 1
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@master
      with:
        persist-credentials: false

    - name: fastpages repo only - convert notebooks and word docs to posts
      if: github.repository == 'fastai/fastpages'
      uses: ./ # use code in this repo instead of a pinned version, for testing.

    - name: convert notebooks and word docs to posts
      if: github.repository != 'fastai/fastpages'
      uses: fastai/fastpages@v2.1.2 # use a pinned version

    - name: setup directories for Jekyll build
      run: |
        rm -rf _site
        sudo chmod -R 777 .

    - name: Jekyll build
      uses: docker://jekyll/jekyll
      with:
        args: jekyll build -V
        
    - name: copy CNAME file into _site if CNAME exists
      run: |
        sudo chmod -R 777 _site/
        cp CNAME _site/ 2>/dev/null || :

    - name: Deploy
      if: github.event_name	== 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
        publish_dir: ./_site
