name: CI
on:
  push:
    branches:
      - master # need to filter here so we only deploy when there is a push to master
  # no filters on pull requests, so intentionally left blank
  pull_request: 

jobs:     
  build-site:
    if: ( github.event.commits[0].message != 'Initial commit' ) || github.run_number > 1
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@master
      with:
        persist-credentials: false

    - name: convert notebooks and word docs to posts
      uses: fastai/fastpages@master # use the code in this repo instead of fastai/fastpages@master, for testing.
      with:
        BOOL_SAVE_MARKDOWN: false
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}

    - name: setup directories for Jekyll build
      run: |
        rm -rf _site
        sudo chmod -R 777 .

    - name: Jekyll build
      uses: docker://jekyll/jekyll
      with:
        args: jekyll build -V
        
    - name: copy CNAME file into _site if CNAME exists
      run: |
        sudo chmod -R 777 _site/
        cp CNAME _site/ 2>/dev/null || :

    # only deploy upon a push to master
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./_site
